# Generated by Django 3.2.6 on 2022-08-12 15:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and Unique', max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Budget Code Slug')),
                ('digits7', models.IntegerField()),
                ('heading', models.CharField(max_length=255)),
                ('vrsHead', models.CharField(max_length=3)),
                ('add_allotment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Budget Code',
                'verbose_name_plural': 'Budget Codes',
            },
        ),
        migrations.CreateModel(
            name='Consumerunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('parent_office', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Consumer Unit Name',
                'verbose_name_plural': 'Consumer Unit Names',
            },
        ),
        migrations.CreateModel(
            name='Procurementprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('tin_no', models.CharField(max_length=13)),
                ('vat_no', models.CharField(max_length=13)),
                ('regpage_no', models.CharField(max_length=13)),
                ('is_registered', models.BooleanField(default=True)),
                ('reg_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Procurement Provider Name',
                'verbose_name_plural': 'Procurement Provider Names',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_cheque', models.BooleanField(default=True)),
                ('taxrate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Income TAX Rate')),
                ('complex_tax', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Complex TAX Amount')),
                ('vatrate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='VAT Rate')),
                ('complex_vat', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name=' Complex VAT Amount')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Created Date')),
                ('updated_at', models.DateField(default=datetime.date.today, verbose_name='Update Date')),
                ('total_exp', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total of Bills')),
                ('total_tds', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax deducted at Source')),
                ('total_vds', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='VAT deducted at Source')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Payable Amount of the Bill')),
                ('consumer_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='altandexp.consumerunit', verbose_name='Consumer Office Name')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expenditure_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alt_exp', to='altandexp.category', verbose_name='Budget Codes')),
                ('item_supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='altandexp.procurementprovider', verbose_name='Select Your Supplier')),
            ],
            options={
                'verbose_name': 'Expenditure',
                'verbose_name_plural': 'Expenditures',
            },
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('alloted_on', models.DateField(verbose_name='Allotment Date')),
                ('alloted_auth', models.CharField(default='23.03.2600.039.51.001.21.000/ A', max_length=70, verbose_name='Vide Ltr Reference')),
                ('alloted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('alloted_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altandexp.consumerunit', verbose_name='For Which Office')),
                ('allotment_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='altandexp.category', verbose_name='Budget Codes')),
            ],
            options={
                'verbose_name': 'Allotment',
                'verbose_name_plural': 'Allotment',
                'ordering': ('allotment_code',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30)),
                ('invoice_date', models.DateField()),
                ('receivevoucher_no', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='altandexp.expenditure')),
            ],
            options={
                'verbose_name': 'Invoice Detail',
                'verbose_name_plural': 'Invoice Details',
                'unique_together': {('invoices', 'invoice_no')},
            },
        ),
    ]
