# Generated by Django 3.2.6 on 2022-08-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altandexp', '0003_expenditure_total_allotments_is'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('refund_on', models.DateField(verbose_name='Trdunded Date')),
                ('refund_auth', models.CharField(default='23.03.2600.039.51.001.21.000/ A', max_length=70, verbose_name='Vide Ltr Reference')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('refund_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_allotments', to='altandexp.category', verbose_name='Budget Codes')),
                ('refund_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altandexp.consumerunit', verbose_name='For Which Office')),
            ],
            options={
                'verbose_name': 'Refund Allotment',
                'verbose_name_plural': 'Refund Allotments',
                'ordering': ('refund_code',),
            },
        ),
    ]
