# Generated by Django 3.2.6 on 2022-08-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altandexp', '0004_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_alloted_amounts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='category',
            name='total_refund_amounts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
