# Generated by Django 3.2.6 on 2022-08-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altandexp', '0006_auto_20220814_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='total_allotments_is',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='total_allotments_codewise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automated. Do not insert any value here', max_digits=12, verbose_name='Progress of Allotments'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='total_expense_codewise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automated. Do not insert any value here', max_digits=12, verbose_name='Progress of Expense'),
        ),
        migrations.AlterField(
            model_name='category',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Progressive Allotment'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='total_exp',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automated. Do not insert any value here', max_digits=12, verbose_name='Total of Single Bills'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automated. Do not insert any value here', max_digits=12, verbose_name='Payable Amount of the Bill'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='total_tds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automated. Do not insert any value here', max_digits=10, verbose_name='Tax deducted at Source'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='total_vds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automated. Do not insert any value here', max_digits=10, verbose_name='VAT deducted at Source'),
        ),
    ]
