# Generated by Django 3.2.6 on 2022-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altandexp', '0008_auto_20220814_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='proggress_of_allotments',
            new_name='progress_of_allotments',
        ),
        migrations.RemoveField(
            model_name='category',
            name='proggress_of_expenses',
        ),
        migrations.AddField(
            model_name='category',
            name='progress_of_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Progressive Expense'),
        ),
        migrations.AlterField(
            model_name='category',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unspent Balance'),
        ),
    ]
