# Generated by Django 3.2.6 on 2022-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altandexp', '0009_auto_20220814_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
