# Generated by Django 3.2.6 on 2022-08-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altandexp', '0010_refund_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='lp_no',
            field=models.CharField(default=1235, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receivevoucher_no',
            field=models.CharField(max_length=8),
        ),
    ]
